parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ConnectHolland\CookieConsentBundle\:
        resource: '../../'
        exclude: '../../{vendor}'

    ConnectHolland\CookieConsentBundle\Cookie\CookieHandler:
        arguments: ["@=service('request_stack').getCurrentRequest()"]

    ConnectHolland\CookieConsentBundle\DOM\DOMParser:
        arguments:
            $cookieConsentTheme: '%ch_cookie_consent.theme%'

    ConnectHolland\CookieConsentBundle\Form\CookieConsentType:
        arguments:
            $cookieCategories: '%ch_cookie_consent.categories%'
